--------------------------------------------------------------------------------------
--  Clarasoft I.T. Solutions
--  Clarasoft Foundation Server
--  CFS Repository DDL (PostgreSQL)
--------------------------------------------------------------------------------------

create database cfsrepo LOCALE 'en_CA.UTF-8';

\c cfsrepo;

CREATE TABLE RPSCFM (
        DOMAIN VARCHAR(32)  NOT NULL ,
        SUBDMN VARCHAR(32)  NOT NULL ,
        CONFIG VARCHAR(32)  NOT NULL ,
        PATH VARCHAR(99) NOT NULL ,
        STORAGE VARCHAR(32) NOT NULL ,
        FORMAT VARCHAR(32)  NOT NULL ,
        ATTR VARCHAR(255)   NOT NULL ,
        DESCID VARCHAR(36)  NOT NULL ,
        CRTU VARCHAR(10)  NOT NULL ,
        CRTD TIMESTAMP NOT NULL ,
        UPDU VARCHAR(10) NOT NULL ,
        UPDD TIMESTAMP NOT NULL,
        PRIMARY KEY (DOMAIN, SUBDMN, CONFIG));

COMMENT ON TABLE RPSCFM IS 'CFS Repository: Configurations';

COMMENT ON COLUMN RPSCFM.DOMAIN IS 'Config. Domain';
COMMENT ON COLUMN RPSCFM.SUBDMN IS 'Config. Sub-domain';
COMMENT ON COLUMN RPSCFM.CONFIG IS 'Configuration Name';
COMMENT ON COLUMN RPSCFM.PATH IS 'Path';
COMMENT ON COLUMN RPSCFM.STORAGE IS 'Storage class';
COMMENT ON COLUMN RPSCFM.FORMAT IS 'Config format';
COMMENT ON COLUMN RPSCFM.ATTR IS 'Storage attributes';
COMMENT ON COLUMN RPSCFM.DESCID IS 'Desc. ID';
COMMENT ON COLUMN RPSCFM.CRTU IS 'Creation User';
COMMENT ON COLUMN RPSCFM.CRTD IS 'Creation Stamp';
COMMENT ON COLUMN RPSCFM.UPDU IS 'Modification USer';
COMMENT ON COLUMN RPSCFM.UPDD IS 'Modification Stamp';

CREATE UNIQUE INDEX RPSCFM_I001 ON RPSCFM (PATH);

CREATE TABLE RPSCFP (
        DOMAIN VARCHAR(32)  NOT NULL ,
        SUBDMN VARCHAR(32)  NOT NULL ,
        CONFIG VARCHAR(32)  NOT NULL ,
        PATH VARCHAR(99) NOT NULL ,
        PARAM VARCHAR(32)  NOT NULL ,
        VALUE VARCHAR(128)  NOT NULL ,
        CRTU VARCHAR(10) NOT NULL ,
        CRTD TIMESTAMP NOT NULL ,
        UPDU VARCHAR(10) NOT NULL ,
        UPDD TIMESTAMP NOT NULL,
        PRIMARY KEY (DOMAIN, SUBDMN, CONFIG, PARAM));

COMMENT ON TABLE RPSCFP IS 'CFS Repository: Parameters' ;

COMMENT ON COLUMN RPSCFP.DOMAIN IS 'Config. Domain';
COMMENT ON COLUMN RPSCFP.SUBDMN IS 'Config. Sub-domain';
COMMENT ON COLUMN RPSCFP.CONFIG IS 'Configuration Name'; 
COMMENT ON COLUMN RPSCFP.PATH IS 'Parameter Path';
COMMENT ON COLUMN RPSCFP.PARAM IS 'Parameter Name';
COMMENT ON COLUMN RPSCFP.VALUE IS 'Parameter Value';
COMMENT ON COLUMN RPSCFP.CRTU IS 'Creation User';
COMMENT ON COLUMN RPSCFP.CRTD IS 'Creation Stamp';
COMMENT ON COLUMN RPSCFP.UPDU IS 'Modification User';
COMMENT ON COLUMN RPSCFP.UPDD IS 'Modification Stamp';

CREATE UNIQUE INDEX RPSCFP_I001 ON RPSCFP (PATH, PARAM);
CREATE UNIQUE INDEX RPSCFP_I002 ON RPSCFP (DOMAIN, SUBDMN, CONFIG, PARAM);
CREATE UNIQUE INDEX RPSCFP_I003 ON RPSCFP (DOMAIN, SUBDMN, CONFIG, PATH, PARAM);

CREATE TABLE RPSENM (
        DOMAIN VARCHAR(32) NOT NULL ,
        SUBDMN VARCHAR(32) NOT NULL ,
        CONFIG VARCHAR(32) NOT NULL ,
        PATH VARCHAR(99) NOT NULL ,
        PARAM VARCHAR(32)  NOT NULL ,
        SEQ INTEGER NOT NULL ,
        VALUE VARCHAR(512) NOT NULL ,
        CRTU VARCHAR(10) NOT NULL ,
        CRTD TIMESTAMP NOT NULL ,
        UPDU VARCHAR(10) NOT NULL ,
        UPDD TIMESTAMP NOT NULL );

COMMENT ON TABLE RPSENM IS 'CFS Repository: Enumerations' ;

COMMENT ON COLUMN RPSENM.DOMAIN IS 'Config. Domain';
COMMENT ON COLUMN RPSENM.SUBDMN IS 'Config. Sub-domain';
COMMENT ON COLUMN RPSENM.CONFIG IS 'Configuration Name'; 
COMMENT ON COLUMN RPSENM.PATH IS 'Parameter Path';
COMMENT ON COLUMN RPSENM.PARAM IS 'Parameter Name';
COMMENT ON COLUMN RPSENM.SEQ IS 'Sequence';
COMMENT ON COLUMN RPSENM.VALUE IS 'Parameter Value';
COMMENT ON COLUMN RPSENM.CRTU IS 'Creation User';
COMMENT ON COLUMN RPSENM.CRTD IS 'Creation Stamp';
COMMENT ON COLUMN RPSENM.UPDU IS 'Modification User';
COMMENT ON COLUMN RPSENM.UPDD IS 'Modification Stamp';


CREATE UNIQUE INDEX RPSENM_I001 ON RPSENM (PATH, PARAM, SEQ);
CREATE UNIQUE INDEX RPSENM_I002 ON RPSENM (DOMAIN, SUBDMN, CONFIG, PARAM, SEQ);
CREATE UNIQUE INDEX RPSENM_I003 ON RPSENM (DOMAIN, SUBDMN, CONFIG, PATH, PARAM, SEQ);



