

--------------------------------------------------------------------------------------
-- Basic CFS client/server example
--------------------------------------------------------------------------------------

INSERT INTO RPSCFM
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'PORT', '11009', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'LOGFILE', './BASIC-ECHO-DAEMON', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'HANDLER', '/usr/lib/clarasoft/clarah', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'HANDLER_CONFIG', 'HANDLERS/EXAMPLES/BASIC-ECHO', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'LISTEN_BACKLOG', '512', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'RES_NUM_HANDLERS', '2', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'MAX_NUM_HANDLERS', '3', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', 'INPROCSERVER', '/usr/lib/clarasoft/libbasic-echo-service.so', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', 'INPROCHANDLER', 'BasicEcho', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', 'PORT', '11009', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

--------------------------------------------------------------------------------------
-- Basic HTTP client example
--------------------------------------------------------------------------------------

INSERT INTO RPSCFM
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', 'PORT', '80', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

--------------------------------------------------------------------------------------
-- Basic Websocket client/server example
--------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------
-- Basic CSAP client/server example
--------------------------------------------------------------------------------------



