--------------------------------------------------------------------------------------
--  Clarasoft I.T. Solutions
--  Clarasoft Foundation Server
--  DDL (PostgreSQL) for example programs
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
-- Basic CFS client/server example
--------------------------------------------------------------------------------------

INSERT INTO RPSCFM
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'PORT', '11009', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'LOGFILE', './BASIC-ECHO-DAEMON', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'HANDLER', '/usr/lib/clarasoft/clarah', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'HANDLER_CONFIG', 'HANDLERS/EXAMPLES/BASIC-ECHO', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'LISTEN_BACKLOG', '512', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'RES_NUM_HANDLERS', '2', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-ECHO', 'DAEMONS/EXAMPLES/BASIC-ECHO', 'MAX_NUM_HANDLERS', '3', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', 'INPROCSERVER', '/usr/lib/clarasoft/libbasic-echo-service.so', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-ECHO', 'HANDLERS/EXAMPLES/BASIC-ECHO', 'INPROCHANDLER', 'BasicEcho', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-ECHO', 'CLIENTS/EXAMPLES/BASIC-ECHO', 'PORT', '11009', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

--------------------------------------------------------------------------------------
-- Basic HTTP client example
--------------------------------------------------------------------------------------

INSERT INTO RPSCFM
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-HTTP', 'CLIENTS/EXAMPLES/BASIC-HTTP', 'PORT', '80', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

--------------------------------------------------------------------------------------
-- Basic Websocket client/server example
--------------------------------------------------------------------------------------

INSERT INTO RPSCFM
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'HANDLERS/EXAMPLES/BASIC-WEBSOCKET', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'CLIENTS/EXAMPLES/BASIC-WEBSOCKET', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'PORT', '11010', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'LOGFILE', './BASIC-WEBSOCKET', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'HANDLER', '/usr/lib/clarasoft/websckh', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'HANDLER_CONFIG', 'HANDLERS/EXAMPLES/BASIC-WEBSOCKET', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'LISTEN_BACKLOG', '512', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'RES_NUM_HANDLERS', '2', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('DAEMONS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'DAEMONS/EXAMPLES/BASIC-WEBSOCKET', 'MAX_NUM_HANDLERS', '3', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'HANDLERS/EXAMPLES/BASIC-WEBSOCKET', 'INPROCSERVER', '/usr/lib/clarasoft/libbasic-websocket-service.so', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('HANDLERS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'HANDLERS/EXAMPLES/BASIC-WEBSOCKET', 'INPROCHANDLER', 'BasicWebsocketEcho', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'CLIENTS/EXAMPLES/BASIC-WEBSOCKET', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CLIENTS', 'EXAMPLES', 'BASIC-WEBSOCKET', 'CLIENTS/EXAMPLES/BASIC-WEBSOCKET', 'PORT', '11010', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  


--------------------------------------------------------------------------------------
-- Basic CSAP client/server example
--------------------------------------------------------------------------------------


INSERT INTO RPSCFM
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CSAP', 'SERVICES', 'BASIC-CSAP-LOCAL', 'CSAP/SERVICES/BASIC-CSAP-LOCAL', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CSAP', 'BROKERS', 'BASIC-CSAP', 'CSAP/BROKERS/BASIC-CSAP', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);
INSERT INTO RPSCFM
  VALUES('CSAP', 'HANDLERS', 'BASIC-CSAP', 'CSAP/HANDLERS/BASIC-CSAP', '*DATABASE', '*SQL', ' ', ' ', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);

INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'PORT', '11011', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'LOGFILE', './BASIC-CSAP', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'HANDLER', '/usr/lib/clarasoft/csapbrkr', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'HANDLER_CONFIG', 'CSAP/BROKERS/BASIC-CSAP', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'LISTEN_BACKLOG', '512', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'RES_NUM_HANDLERS', '2', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'DAEMONS', 'BASIC-CSAP', 'CSAP/DAEMONS/BASIC-CSAP', 'MAX_NUM_HANDLERS', '3', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CSAP', 'BROKERS', 'BASIC-CSAP', 'CSAP/BROKERS/BASIC-CSAP', 'SERVICE_MODE', '*SINGLE', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSENM
  VALUES('CSAP', 'BROKERS', 'BASIC-CSAP', 'CSAP/BROKERS/BASIC-CSAP', 'SERVICES', 1, 'CSAP/HANDLERS/BASIC-CSAP', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CSAP', 'HANDLERS', 'BASIC-CSAP', 'CSAP/HANDLERS/BASIC-CSAP', 'INPROCSERVER', '/usr/lib/clarasoft/libbasic-csap-service.so', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'HANDLERS', 'BASIC-CSAP', 'CSAP/HANDLERS/BASIC-CSAP', 'INPROCHANDLER', 'BasicCSAPEcho', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  

INSERT INTO RPSCFP
  VALUES('CSAP', 'SERVICES', 'BASIC-CSAP-LOCAL', 'CSAP/SERVICES/BASIC-CSAP-LOCAL', 'HOST', 'localhost', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP
  VALUES('CSAP', 'SERVICES', 'BASIC-CSAP-LOCAL', 'CSAP/SERVICES/BASIC-CSAP-LOCAL', 'PORT', '11011', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP);  
INSERT INTO RPSCFP                                                 
  VALUES('CSAP', 'SERVICES', 'BASIC-CSAP-LOCAL', 'CSAP/SERVICES/BASIC-CSAP-LOCAL', 'SERVICE', 'CSAP/HANDLERS/BASIC-CSAP', '*CFS', CURRENT_TIMESTAMP, '*CFS', CURRENT_TIMESTAMP); 

